### ISSUE TITLE
Web Dashboard / Admin UI?

### ISSUE THREAD

**Issue by Nezteb** [remotestorage/remotestorage-server#6]
When experimenting/debugging, I like having some sort of UI for my databases, such as [sqlitebrowser for SQLite](https://github.com/sqlitebrowser/sqlitebrowser). For `remoteStorage`, I think it'd make sense to have a simple JS web UI that users can interact with their data from.

[`deployd` was a cool API builder that is no longer actively maintained](https://github.com/deployd/deployd), but it had [a cool web dashboard](http://docs.deployd.com/docs/getting-started/include-all.html#s-Your%20first%20Deployd%20API) which could be used for basic CRUD operations in your database.

[The `starter-kit` has a portal](https://github.com/remotestorage/starter-kit/tree/master/portal), but the `starter-kit` hasn't been updated since 2015 so I don't know how relevant that is.

I wasn't sure if this should be made in https://github.com/remotestorage/remotestorage.js or not, so I opted for this server repo since it'd make sense for the server to serve this web/admin UI. 😅

**Comment by raucao** [comment]
Hi @Nezteb,

This server project is an outdated one, but no need to open server project issues on other server repos for this. Here's a file browser, which lets you inspect your storage with any RS-compatible server:

* https://inspektor.5apps.com
* Source code: https://gitea.kosmos.org/raucao/inspektor

Since Gitea doesn't federate quite yet, feel free to ask questions or propose features for this app on the [RS forums](https://community.remotestorage.io.). (And if you actually want to contribute code to it, let me know and I send you an invite for a Kosmos account, so you can open PRs on that Gitea.)
